version: '3.8'

services:
  microid-app:
    container_name: microid-app
    build:
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      microid-db:
        condition: service_healthy
    restart: on-failure
    links:
      - microid-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DB_URL: jdbc:mysql://microid-db:3306/microid
      DB_USER: microidapp
      DB_PASSWORD: microid

  microid-db:
    container_name: microid-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: midadmin
      MYSQL_DATABASE: microid
      MYSQL_USER: microidapp
      MYSQL_PASSWORD: microid
    ports:
      - 3306:3306
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10