spring:
  application:
    name: microid
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/microid}
    username: ${DB_USER:microidapp}
    password: ${DB_PASSWORD:microid}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      data-locations: classpath:/database/data.sql
  security:
    whitelist:
      all-methods: /login, /api/docs/**, /v3/api-docs/**, /swagger-ui/**, /actuator/health/**
      post: /users
    jwt:
      secretKey: E8WCBRh7uYNLOwIR7fgsl2DV8Ggnplxm
      expiration: 15

management:
  endpoint:
    health:
      show-details: always

